#!/bin/sh

# welcome to the 21th century
alias cat='bat'
alias df='duf'
alias diff='delta'
alias du='dust'
alias grep='rg'
alias ls='exa'
alias top='btop'
alias tree='erd -IH'
alias htop='btm'
alias vi='nvim'
alias vim='nvim'
alias watch='viddy'

# safety first
alias mkdir='mkdir -pv'
alias mv='mv -iv'
alias rm='rm -v'
alias cp='cp -iv'

# reject tradition, embrace modernity
alias copilot='copilot --yolo'

# ls options
alias ls='ls -h --color=always --group-directories-first'
alias la='ls -al'              # all files and dirs
alias lh='ls -a | egrep "^\."' # only hidden
alias ll='ls -l'               # long format
alias lt='ls -aT | bat'        # tree listing
alias lu='ll -tU | tail -r'

alias l='ls'

# correct typos
alias pytohn='python'
alias vu='nvim'
alias vo='nvim'
alias co='cp'

# git stuff
alias g='git'
alias gti='git'
alias gbr='git branch'
alias gcm='git commit $(git ls-files -m | fzf --preview "git diff --color=always -- {}")'
alias gco='git checkout'
alias gdf='git diff'
alias gdt='git difftool'
alias gll='git log --oneline --no-merges'
alias gpl='git pull'
alias gps='git push'
alias gst='git status'

# vim stuff
alias vsp='nvim -O'
alias vdf='nvim -d'
alias vtb='nvim -p'
alias fastvim='nvim -n -u NONE -i NONE -N'

# python stuff
alias black='uvx ruff format'
alias git-sim='uvx git-sim'
alias isort='uvx ruff check --select I,RUF022 --fix'
alias radon='uvx radon'
alias ruff='uvx ruff'
alias sqlfluff='uvx sqlfluff fix --dialect postgres'
alias vd='uvx --with openpyxl --with pyarrow visidata'
alias yt-dlp='uxx yt-dlp'
alias mypy='uvx mypy --cache-dir .mypy_cache --sqlite-cache .'

# misc
alias stow-dot="stow --restow -v --no-folding --dotfiles -t ~ -d ~/.dotfiles ."
alias encf="openssl enc -e -aes256 -in"
alias decf="openssl enc -d -aes256 -in"
alias weather="curl wttr.in"
alias wifi="nmcli dev wifi show-password"
alias rss="newsraft"
alias pacman-hist="expac --timefmt='%Y-%m-%d %T' '%l\t%w\t%n' | sort"
alias hashfiles="fd -t f | sort | xargs -I{} md5sum {}"
